services:
    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/
            - ./docker/conf/nginx.conf:/etc/nginx/nginx.conf:ro
        networks:
            - parser

    app:
        image: parser/app
        build:
            context: ./docker
            dockerfile: Dockerfile
        container_name: app
        restart: unless-stopped
        expose:
            - 9000:9000
        volumes:
            - .:/var/www
        networks:
            - parser
        environment:
            CONTAINER_ROLE: app

    scheduler:
        image: parser/app
        container_name: scheduler
        restart: unless-stopped
        expose:
            - 9000:9000
        volumes:
            - .:/var/www
        networks:
            - parser
        environment:
            CONTAINER_ROLE: scheduler

    mysql:
        image: mariadb
        container_name: mysql
        restart: unless-stopped
        ports:
            - 3306:3306
        volumes: 
            - mysql:/var/lib/mysql
        environment:  
            MYSQL_ROOT_PASSWORD: hTv27bT32a
            MYSQL_DATABASE: parser
        networks:
            - parser

    mail:
        image: mailhog/mailhog
        container_name: mailhog
        restart: unless-stopped
        ports:
            - 1025:1025
        networks:
            - parser

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        ports:
            - 6379:6379
        volumes:
            - redis:/root/redis
        environment:
            - REDIS_PASSWORD=haf62vFa21
        networks:
            - parser

volumes:
    mysql:
        driver: local
    redis:
        driver: local

networks:
    parser:
        driver: bridge